import { ITicket } from '../components/Ticket';

export const tickets: Array<ITicket> = [
  {
    id: 1,
    price: 13400,
    destinationsThere: 'MOW - HKT',
    destinationsBack: 'MOW - HKT',
    timeThere: '10:45 - 08:00',
    timeBack: '11:20 - 00:50',
    totalTimeThere: '21ч 15м',
    totalTimeBack: '13ч 30м',
    transfersNumberThere: 2,
    transfersNumberBack: 1,
    transferPlacesThere: 'HKG, JNB',
    transferPlacesBack: 'HKG',
  },

  {
    id: 2,
    price: 13400,
    destinationsThere: 'MOW - HKT',
    destinationsBack: 'MOW - HKT',
    timeThere: '10:45 - 08:00',
    timeBack: '11:20 - 00:50',
    totalTimeThere: '21ч 15м',
    totalTimeBack: '13ч 30м',
    transfersNumberThere: 2,
    transfersNumberBack: 1,
    transferPlacesThere: 'HKG, JNB',
    transferPlacesBack: 'HKG',
  },

  {
    id: 3,
    price: 13400,
    destinationsThere: 'MOW - HKT',
    destinationsBack: 'MOW - HKT',
    timeThere: '10:45 - 08:00',
    timeBack: '11:20 - 00:50',
    totalTimeThere: '21ч 15м',
    totalTimeBack: '13ч 30м',
    transfersNumberThere: 2,
    transfersNumberBack: 1,
    transferPlacesThere: 'HKG, JNB',
    transferPlacesBack: 'HKG',
  },

  {
    id: 4,
    price: 13400,
    destinationsThere: 'MOW - HKT',
    destinationsBack: 'MOW - HKT',
    timeThere: '10:45 - 08:00',
    timeBack: '11:20 - 00:50',
    totalTimeThere: '21ч 15м',
    totalTimeBack: '13ч 30м',
    transfersNumberThere: 2,
    transfersNumberBack: 1,
    transferPlacesThere: 'HKG, JNB',
    transferPlacesBack: 'HKG',
  },

  {
    id: 5,
    price: 13400,
    destinationsThere: 'MOW - HKT',
    destinationsBack: 'MOW - HKT',
    timeThere: '10:45 - 08:00',
    timeBack: '11:20 - 00:50',
    totalTimeThere: '21ч 15м',
    totalTimeBack: '13ч 30м',
    transfersNumberThere: 2,
    transfersNumberBack: 1,
    transferPlacesThere: 'HKG, JNB',
    transferPlacesBack: 'HKG',
  },
];
